language: node_js
before_install:
  - rvm install 2.2.2
  - sudo apt-get install pandoc
  - gem install asciidoctor
script:
  - ./Tools/generate_document.sh
  - ./Tools/install.sh
  - node ./Tools/genpdf.js
