sudo: required
language: objective-c
osx_image: xcode9.3
before_install:
- rvm install 2.5.1 --disable-binary
- brew install pandoc
- gem install asciidoctor
script:
- "./Tools/gendocs.sh"
deploy:
  provider: releases
  api_key:
    secure: D9F86C+yin7z4G+5/96xPXjUICMGyFyZ3rG4kTZtUtyrVShHbN8Gv3s8ChNv+tbiDyvbLavHpHzSuOb91/eAmxJdNrQTCGTQL2o2ReRvisPf4FlIInzLzQUckBfTg54jlB+wulk+BToPcgqAFXCE23Ph2nKoIK/OVvEfQVehF+u5Z68lWlci9yBdD45FeYq7X1t0cnc7yZp2eCssDuQ5+11dUk5nJekpYiZfjC6ay+RCwDWByLWYuFuSY7b5PCYBhvpBabf0XPkdSTHfIYCGRJpSWhk8zqOFaIN+HPym6fFPTDY++XPYV1DPJwqzSvyJ+KOaoPi/S81joM0fIdvBsgPLufVK86KvOyB8BLbNsK175OJRycMP1zpldzJszqARWFVNKeLrZ0zLCWsag+0BVCTMLQcqjH6qZ3P/snswxiycVTKrc+PUbHrM5OskXD26YFUNKF8u9rKKY8Cfl0wAJT9Z7VLyy1dMex398P4MpxYKj5EdKaU5w7H6vgQVs13GVYk85UsxVRUHmR/s5VDEblyNCvSFGUuC8sdPYT31VT6i5BSYYLT35YPZgGM1c1t4O+n9drNAyaySHbWE5nDri0+c4tvlHMNESXEGXRYODCmiFCmQ8AB6RVHmxMGeyavytexOlaaxMdoocdehBo8X8Ty/pkDV9bHTFUVfGr/k5w4=
  file:
    - "$TRAVIS_BUILD_DIR/Generated/MSTG-EN.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/MSTG-EN.doc"
  skip_cleanup: true
  overwrite: true
  on:
    repo: OWASP/owasp-mstg
    branch: 964/versioning_releasing
