sudo: required
language: objective-c
osx_image: xcode9.3
before_install:
- rvm install 2.5.1 --disable-binary
- brew install pandoc
- brew cask install calibre
- npm install -g gitbook-cli
- gem install asciidoctor
script:
- "./Tools/gendocs.sh"
global:
  secure: ch2N8TSIyCLtBy9KgbzGKy4LA9KW0AMVV3pHzwdmNhiF2L4ZKAWH45bnC5bLbPBNFzqxPp813tOVJ8cjjanBuKnf06WcvQjsVoQHU5/1VHleW/WSYMKZef+a4+TFMo8o+RDiSAcsfwM/5PtnMO0xkjn0zLno8KOx4J2jEn7/bTVNN8UFX+LMY1H3G6BZX8UpPoo/Rud1eu3mtzT+DgJ1t7nP1YY02ylmK1OY4W+wSCpR55K6ixAupXCIwFLA1/cBfmj/ZNzoXz74dmBY10vfcLNKN77JiX0ei10LucwZz3RMGPPJeTwM2ecRg9qvYANhkrd2t4z5R9oquv212Kt69nybQRTPwZpnnxY5+S/qoJlm1e6CTe+bjWsO6hnCDoM4WvkeWThq9dgjyeYpJGLloSkIuS6GjW9MqK0hGBzxj5zYm0Ri2OzTbHYr3q64L0095Fzj68ieEg/2DYbA067ww2FZ80BTgUF4B58ichThGV+ONiiX0dwWgM2M2u7PegOmWcVtSgbe+B4NJ2sKAjQssBXKUoVEI+7c8AnGyBfuI9onuUD3yl9W70RS9kmldltFvz/Tk8u6pJcz352k+Y/LJiqqMVWo4yc/Pwl9VG4YLgkeMYo/SWCaf+yJRsD7wDp6AvJdJ6R8JIzZLjHFEU7qMuZbUcS4LNpS2/YXLv/VYO4=
deploy:
  provider: releases
  api_key:
    secure: U99LVZFmIhWeXlpFeePdnDTrX4IGmmfrI8/LVht91P6YAQMhxIlOar/ba2AGGzuZX6ZSkSFKaATd6m1fEUmNexSwMfoVStQnRNctZN6l6PPylo8tvrZfgbAryMwHMTnjYIm/Ym0iCsZrwa9+GiJ03/JKdqE30QKK0PLQ4VRvBIUyblsLjDdPai/UqchE5AnYzCVXB5YKDX5U1y29DNdLRfd5CLjpwZOtgIkshOaK0FGuelciVNDT+hPZWbGWBBfCbDmdlW2GZPwnPGaa4BoA57VBXf8NgOACJT6GRbtw5m9x6H/xYB2/9I/ieccpi07gi0/X0TuvafU/LXOjhir2J4rTXRyNJ7WSQiVTSNYZS7IZ7OyiBVENH9BOrVWshIEXR4eQolo0RRnmJv1CcXTc9WyA8jiZWns/X3eCQo96t9s31etIOdQCBb2W6iBV31lzMHqseURH7DlXCKQ7imrID4mdCnzG2DdpV9/2aHmreKJKqu0DZMvwqdr9BYb9sJNJJkSD+BVL5OSCjGqvmmImIBcmIjhcbufZOTuRINLD1UfZJ41tV4TR3u8OC0zJeOosk5BqQwdJgsf1Z3CV7adiXE/tHHyRsyoE79W9DPVTX4R6NqxOhm9a7/IGJv532W65UnwXcvfRmYEctS5K2hGSTmVDn/wL90mr67YOceiKtj0=
  file:
    - "$TRAVIS_BUILD_DIR/Generated/MSTG-en.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/MSTG-EN.docx"
  skip_cleanup: true
  overwrite: true
  name: "Intermediate update $TRAVIS_TAG"
  body: "Intermediate update ($TRAVIS_TAG). See CHANGELOG.md for updates on intermediate update releases."
  on:
    repo: OWASP/owasp-mstg
    tags: true
