name: codespell

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

env:
  WORDS_LIST: ba,compliancy,firt,ist,keypair,ligh,ser,synopsys,zuser

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          ignore_words_list: $WORDS_LIST
          uri-ignore-words-list: $WORDS_LIST
